spring:
  application:
    name: mod-entities-links
  datasource:
    continue-on-error: true
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
    password: ${DB_PASSWORD:folio_admin}
    username: ${DB_USERNAME:folio_admin}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    consumer:
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:50}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
    producer:
      acks: all
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 5
  cache:
    cache-names:
      - authority-source-files-cache
      - authority-mapping-rules-cache
      - authority-linking-rules-cache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=3600s

folio:
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://localhost:9130}
  system-user:
    username: mod-entities-links
    password: ${SYSTEM_USER_PASSWORD:mod-entities-links}
    lastname: System
    permissionsFilePath: permissions/mod-entities-links-permissions.csv
  kafka:
    topics:
      - name: links.instance-authority
        numPartitions: ${KAFKA_INSTANCE_AUTHORITY_TOPIC_PARTITIONS:10}
        replicationFactor: ${KAFKA_INSTANCE_AUTHORITY_TOPIC_REPLICATION_FACTOR:}
    listener:
      authority:
        concurrency: ${KAFKA_AUTHORITIES_CONSUMER_CONCURRENCY:1}
        topic-pattern: ${KAFKA_AUTHORITIES_CONSUMER_PATTERN:(${folio.environment}\.)(.*\.)inventory\.authority}
        group-id: ${folio.environment}-mod-entities-links-authorities-group
  instance-authority:
    change:
      numPartitions: ${KAFKA_INSTANCE_AUTHORITY_CHANGE_PARTITIONS:100}

  retry:
    enabled: true
  tenant:
    validation:
      enabled: true
  logging:
    request:
      enabled: true
    feign:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,liquibase,threaddump,heapdump,loggers
      base-path: /admin
  endpoint:
    loggers:
      enabled: true
server.port: 8081
